### PR TITLE
[wip] Feature: updates GetData.sh to use new filenames

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by de-code** [comment]
Looks good, I was under the impression that James had looked into fixing it as well?

**Comment by JGilbert-eLife** [comment]
I am, but @lsh-0's  fix looks better than where I was going.

That said, I am having trouble getting this revised script to run locally. For some reason, this line:

` 		name=$(echo $i | sed -n "s/ejp_query_tool_query_id_SQL_\(.\+\)_${tday}_eLife\.csv$/\1/p")`

is giving me completely empty file names and I can't work out why.

**Comment by JGilbert-eLife** [comment]
With the caveat that I have very little experience using regexs, I have discovered that this fix works for running locally on my mac if I change:

`name=$(echo $i | sed -n "s/ejp_query_tool_query_id_SQL_\(.\+\)_${tday}_eLife\.csv$/\1/p")`

to

`name=$(echo $i | sed -n "s/ejp_query_tool_query_id_SQL_\(.*\)_${tday}_eLife\.csv$/\1/p")`

I think it might be correct to remove the backslash after the dot, but am more fuzzy on why switching from + to * makes a difference here. @de-code, is this something you can explain for me? Would making this change have any horrific consequences?

**Comment by JGilbert-eLife** [comment]
Argh. I see what's going on. I've basically switched from `\+` to `*`, since + needs to be escaped and * doesn't. Got it. Told you I had no idea what I was doing.

I'm still not sure why `\+` wouldn't work when I run it in my mac terminal . . .

**Comment by lsh-0** [comment]
>  since + needs to be escaped and * doesn't. Got it. Told you I had no idea what I was doing.

... and you think I knew about that arcane bit of knowledge before I tripped over it in the same place? ;)

I'll take another look today to make sure what is working for you on a mac also works in linux, where this thing is run.

**Comment by JGilbert-eLife** [comment]
Cheers @lsh-0!

**Comment by lsh-0** [comment]
>  I've basically switched from \+ to *, since + needs to be escaped and * doesn't.

I think I've encountered something like this before. There are subtle differences between the `sed` used on a mac vs linux, and even in linux there are different flavours too.

Here's mine:

```
$ sed --version
sed (GNU sed) 4.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
```

I'm betting the one on your mac is different and licenced under the BSD (rather than the GPL).

One of these subtle differences is macs not supporting `\+` (one or more) without the `-E` flag for 'extended regular expressions'. Linux also have a 'extended regular expression' flag, but it's `-r`, so I couldn't use either one and remain compatible. I've gone back to using `.*` (zero or more) because it's compatible with both.

**Comment by lsh-0** [comment]
I've gone through it manually, creating the database, running GetData and it appears to be generating the report again.

I am getting this in the output: 

> ./output/Country_1.csv:33472: expected 2 columns but found 3 - extras ignored

from this content (leading [...] digits are line numbers, not file content):

```csv
[33471] 44448,United States
[33472] 44449,Korea (North), Democratic People's Republic of
[33473] 44450,Chile
```

I shouldn't think that's a problem as "Korea (North)" is as good as the full thing.

I'm going to merge this and then we can see if Paul Kelly's reports start coming through again

**Comment by lsh-0** [comment]
it's looking good. I'm updating lax now and then will re-export PKs queries.

Here's the gap if anyone is interested:

```bash
-rw-rw-r-- 1 elife elife  4945755 Jun 19 12:15 paper_history2019-06-19_Appeals.csv
-rw-rw-r-- 1 elife elife  4479415 Jun 19 12:15 paper_history2019-06-19.csv
-rw-rw-r-- 1 elife elife        0 Jun 20 12:15 paper_history2019-06-20_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 20 12:15 paper_history2019-06-20.csv
-rw-rw-r-- 1 elife elife        0 Jun 21 12:15 paper_history2019-06-21_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 21 12:15 paper_history2019-06-21.csv
-rw-rw-r-- 1 elife elife        0 Jun 22 12:15 paper_history2019-06-22_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 22 12:15 paper_history2019-06-22.csv
-rw-rw-r-- 1 elife elife        0 Jun 23 12:15 paper_history2019-06-23_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 23 12:15 paper_history2019-06-23.csv
-rw-rw-r-- 1 elife elife        0 Jun 24 12:15 paper_history2019-06-24_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 24 12:15 paper_history2019-06-24.csv
-rw-rw-r-- 1 elife elife        0 Jun 25 12:15 paper_history2019-06-25_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 25 12:15 paper_history2019-06-25.csv
-rw-rw-r-- 1 elife elife        0 Jun 26 12:15 paper_history2019-06-26_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 26 12:15 paper_history2019-06-26.csv
-rw-rw-r-- 1 elife elife        0 Jun 27 12:15 paper_history2019-06-27_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 27 12:15 paper_history2019-06-27.csv
-rw-rw-r-- 1 elife elife        0 Jun 28 12:15 paper_history2019-06-28_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 28 12:15 paper_history2019-06-28.csv
-rw-rw-r-- 1 elife elife        0 Jun 29 12:15 paper_history2019-06-29_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 29 12:15 paper_history2019-06-29.csv
-rw-rw-r-- 1 elife elife        0 Jun 30 12:15 paper_history2019-06-30_Appeals.csv
-rw-rw-r-- 1 elife elife        0 Jun 30 12:15 paper_history2019-06-30.csv
-rw-rw-r-- 1 elife elife  4984718 Jul  1 06:33 paper_history2019-07-01_Appeals.csv
-rw-rw-r-- 1 elife elife  4514648 Jul  1 06:33 paper_history2019-07-01.csv
```

**Comment by lsh-0** [comment]
alright, queries generated and uploaded. I'll shoot PK an email if he's not following this ticket

**Comment by JGilbert-eLife** [comment]
Thanks for updating the code, @lsh-0 - the North Korea issue is not ideal but causes few problems for actual use of this reporting process. It should be dealt with by reconfiguring the submission system if at all.

**Pull request merged**
